### ISSUE TITLE
Download Fails on iOS

### ISSUE THREAD

**Issue by CassySpencer** [broven/canvas2image#2]
Hi, I love this script but on my iPhone, I see the following error:

[http://i.imgur.com/QVXSJAK.png](url)

It seems that iOS can't download Data URLs.

Can you help?

**Comment by broven** [comment]
seem it's a bug, working on it

**Comment by CassySpencer** [comment]
Thank you so much.  I'm new to JavaScript and so I am a little lost.   You help is very much appreciated.

**Comment by broven** [comment]
seems there is no approach to do this only use JS.

**Comment by CassySpencer** [comment]
I don't understand.

**Comment by broven** [comment]
My english is limited. 
you can't use this lib to save canvas data image on Iphone

**Comment by CassySpencer** [comment]
Are you 100% sure?

**Comment by broven** [comment]
For me,  yes. I'v  tried any idea that i come up. shame for that.

**Comment by CassySpencer** [comment]
How is this website making it save on iOS?
http://mrdoob.com/projects/harmony/
